spring:
  profiles:
    active: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  servlet:
    context-path: /api/