spring:
  profiles:
    active: docker-dev
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  servlet:
    context-path: /api/